name: Deploy

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SSH_USER: ${{ secrets.SSH_USER }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy
      run: |
        # Добавляем сервер в known_hosts
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
        
        # Создаем директорию и копируем файлы
        ssh $SSH_USER@$SERVER_IP "mkdir -p /opt/jipping-app"
        scp -r . $SSH_USER@$SERVER_IP:/opt/jipping-app/
        
        # Деплоим
        ssh $SSH_USER@$SERVER_IP << 'EOF'
          cd /opt/jipping-app
          docker-compose down
          docker-compose up -d --build
        EOF
